### ISSUE TITLE
Pearson hash using wrong table

### ISSUE THREAD

**Issue by 10-10-11-zz** [ze-phyr-us/pearhash#1]
Hi Vita,
your implementation of pearson hash uses a wrong table.
The table must contain **ALL** numbers from 0-255 in any random order without duplicates.
Therefore using `randint` to get the values is wrong. 
`[ generator.randint(0, 255) for i in range(256) ]` generates a table with duplicates!

You might want to use something like this

```
table = range(256)
generator = random.Random()
generator.seed(seed)
generator.shuffle(table)
assert(sum(table) == (255*(255 +1))/2)
self.table = table
```

**Comment by vitawasalreadytaken** [comment]
Ouch! Thanks a lot for taking the time to read the code. It is now fixed and released to PyPI (pearhash==1.0.1).
